Update patch set 1
Patch Set 1: Code-Review-1

Sphinx requires a conf.py file:

  Error: Config directory doesn't contain a conf.py file.

Patch-set: 1
Reviewer: Gerrit User 15 <15@f2a2391d-0403-4fa5-b183-4056999a8a09>
Label: Code-Review=-1